fig_name: 
    "lines.pdf"
config_file:
    "configs/icra2020_fewshot_performance.xml"
root_dir:
    "/media/tynguyen/tynguyen_SSD/ICRA2020/test_logs/cleaned_real_test_set/plots"
saving_dir:
    ""
cols_per_file:
    6
extension:
    ".txt"
skip_rows:
    1
xlim:
    [-10,600]
ylim:
    [0,1]
xlabels:
    ['zero-shot','one-shot','5-shot','50-shot','200-shot', 'all-shot']
xticks:
    [0,1,5,50,200,600]
x_values:
    [0,1,5,50,200,575]
legends:
    ['N-shot Detection mAP']
reduce_func:
    'mean'

